name-template: 'Release {{version}}'
tag-template: '{{version}}'
categories:
  - title: "Features"
    labels:
      - feature
  - title: "Bug Fixes"
    labels:
      - bug
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  # Yet another release!
  ## Changes
  $CHANGES