name: CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         lfs: 'true'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Lint source code
        run: make lint
