name: Cleanup PR Images

on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python and install requests
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests

      - name: Delete PR Docker tag
        run: |
          python .github/scripts/delete_docker_tag.py ${{ secrets.DOCKER_USERNAME }} package-name pr-${{ github.event.pull_request.number }}