name: Hotfix Workflow

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/python-template

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dev/**'

jobs:
  hotfix:
    if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Bump patch version and get new tag
        id: bump_patch
        run: |
          NEW_VERSION=$(python3 .github/scripts/bump_patch.py)
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag and push (Hotfix)
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Hotfix Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:stable
          platforms: linux/amd64,linux/arm64

      - name: Cherry-pick hotfix into dev branch
        run: |
          HOTFIX_COMMIT=$(git rev-parse HEAD)
          git checkout dev
          git cherry-pick $HOTFIX_COMMIT
          git push origin dev

      - name: Rebuild DEV "latest" Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64